import { useMemo, useState } from 'react'
import { Badge, Card, EmptyState, Table, Td, Th, Thead, Tr } from './ui/Display'
import { Button } from './ui/Button'
import { Input } from './ui/FormElements'

interface Props { module?: string; eta?: string }

const details: Record<string, { icon: string; subtitle: string; metrics: string[][]; tabs: string[] }> = {
  Orders: { icon: 'shopping_bag', subtitle: 'Track fulfilment, payments and customer orders.', metrics: [['Open Orders','28'],['Processing','12'],['Revenue Today','ZMW 24,850'],['Returns','3']], tabs: ['All Orders','Processing','Completed','Returns'] },
  Warehouses: { icon: 'warehouse', subtitle: 'Manage locations, capacity and stock distribution.', metrics: [['Locations','4'],['Capacity','18,500'],['Utilisation','76%'],['Transfers Today','14']], tabs: ['Locations','Capacity','Zones'] },
  'Stock Adjustments': { icon: 'inventory', subtitle: 'Review and reconcile stock corrections.', metrics: [['Pending Review','6'],['Approved Today','18'],['Value Changed','ZMW 8,420'],['Variance','1.8%']], tabs: ['Adjustments','Cycle Counts','History'] },
  'Employee Detail': { icon: 'badge', subtitle: 'Employee profile, performance and employment records.', metrics: [['Tenure','3.8 yrs'],['Leave Balance','18 days'],['Performance','4.7 / 5'],['Attendance','97.8%']], tabs: ['Overview','Documents','Performance','Payroll'] },
  'Leave Management': { icon: 'event_available', subtitle: 'Coordinate leave requests, balances and team availability.', metrics: [['On Leave Today','8'],['Pending Requests','12'],['Approval Rate','92%'],['Days Scheduled','148']], tabs: ['Requests','Calendar','Balances','Policies'] },
  'Finance — Invoices': { icon: 'account_balance', subtitle: 'Monitor cash flow, receivables and financial performance.', metrics: [['Cash Position','ZMW 847,250'],['Receivables','ZMW 124,800'],['Payables','ZMW 98,420'],['Net Margin','24.8%']], tabs: ['Overview','Transactions','Accounts','Reconciliation'] },
  'Payment Recording': { icon: 'payments', subtitle: 'Record, allocate and reconcile incoming payments.', metrics: [['Received Today','ZMW 48,120'],['Unallocated','ZMW 3,200'],['Transactions','36'],['Success Rate','99.2%']], tabs: ['Incoming','Allocations','Reconciliation'] },
  'AR Aging Report': { icon: 'query_stats', subtitle: 'Analyse overdue balances and collection risk.', metrics: [['Current','ZMW 82,500'],['1–30 Days','ZMW 28,100'],['31–60 Days','ZMW 9,200'],['60+ Days','ZMW 5,000']], tabs: ['Summary','Customers','Invoices'] },
  Payroll: { icon: 'account_balance_wallet', subtitle: 'Process compliant payroll, benefits and statutory deductions.', metrics: [['Gross Payroll','ZMW 684,200'],['Net Payroll','ZMW 512,480'],['Employees','124'],['Next Run','25 Sep']], tabs: ['Payroll Runs','Payslips','Deductions','Benefits'] },
  'Workflow Automation': { icon: 'account_tree', subtitle: 'Build automations that connect every business process.', metrics: [['Active Workflows','18'],['Runs This Month','2,847'],['Success Rate','98.6%'],['Time Saved','184 hrs']], tabs: ['Workflows','Run History','Templates'] },
  'AI & Analytics': { icon: 'auto_awesome', subtitle: 'Turn operational data into decisions and forecasts.', metrics: [['Insights','247'],['Forecast Accuracy','94.2%'],['Risks Detected','12'],['Reports','38']], tabs: ['Executive Insights','Forecasts','Anomalies'] },
  'Organization Settings': { icon: 'tune', subtitle: 'Configure company information, branches and defaults.', metrics: [['Branches','4'],['Users','148'],['Active Modules','12'],['Plan','Enterprise']], tabs: ['General','Branches','Preferences','Branding'] },
  'Roles & Permissions': { icon: 'admin_panel_settings', subtitle: 'Control access with precise role-based permissions.', metrics: [['Roles','8'],['Users','148'],['Policies','24'],['Reviews Due','3']], tabs: ['Roles','Users','Policies','Audit'] },
  Expenses: { icon: 'receipt_long', subtitle: 'Capture, approve and analyse every business expense.', metrics: [['This Month','ZMW 184,200'],['Pending Claims','18'],['Approved','92%'],['Budget Remaining','ZMW 420,800']], tabs: ['Overview','Claims','Categories','Budgets'] },
  Loans: { icon: 'request_quote', subtitle: 'Manage employee loans, repayment schedules and balances.', metrics: [['Active Loans','36'],['Outstanding','ZMW 214,500'],['Due This Month','ZMW 38,420'],['On Schedule','96%']], tabs: ['Applications','Active Loans','Repayments','Policies'] },
  Reports: { icon: 'insights', subtitle: 'Explore real-time reports across every SmartBiz module.', metrics: [['Saved Reports','28'],['Dashboards','8'],['Scheduled','14'],['Shared Today','6']], tabs: ['Report Centre','Favourites','Scheduled','Exports'] },
  'CRM Pipeline': { icon: 'view_kanban', subtitle: 'Convert opportunities with a clear, collaborative sales pipeline.', metrics: [['Pipeline Value','ZMW 1.84M'],['Open Deals','42'],['Win Rate','38.6%'],['Closing Soon','12']], tabs: ['Pipeline','Contacts','Activities','Forecast'] },
  Marketplace: { icon: 'storefront', subtitle: 'Extend SmartBiz with trusted apps and industry integrations.', metrics: [['Available Apps','48'],['Installed','8'],['Connected','7'],['Updates','3']], tabs: ['Discover','Installed','Categories','Connections'] },
  'Security Center': { icon: 'shield_lock', subtitle: 'Monitor access, security posture and account risk.', metrics: [['Security Score','94%'],['Active Sessions','32'],['Open Alerts','3'],['MFA Coverage','87%']], tabs: ['Overview','Alerts','Sessions','Policies'] },
  'Audit Logs': { icon: 'manage_search', subtitle: 'Review a tamper-evident history of important business activity.', metrics: [['Events Today','1,284'],['High Risk','2'],['Users Active','84'],['Retention','365 days']], tabs: ['All Events','Access','Data Changes','Exports'] },
  'Subscription & Billing': { icon: 'workspace_premium', subtitle: 'Manage your plan, usage, invoices and payment method.', metrics: [['Current Plan','Enterprise'],['Monthly Usage','72%'],['Next Invoice','ZMW 4,820'],['Renewal','01 Oct']], tabs: ['Plan','Usage','Billing History','Payment Method'] },
  Accounting: { icon: 'account_balance', subtitle: 'Run compliant books, reconciliations and financial statements.', metrics: [['Accounts','64'],['Unposted Journals','8'],['Bank Variance','ZMW 1,240'],['Period','September']], tabs: ['Chart of Accounts','Journals','General Ledger','Reconciliation','Statements'] },
  Projects: { icon: 'folder_managed', subtitle: 'Plan delivery, budgets, milestones and team capacity.', metrics: [['Active Projects','18'],['On Track','14'],['At Risk','3'],['Budget Used','68%']], tabs: ['Portfolio','Board','Milestones','Timesheets','Budgets'] },
  Assets: { icon: 'precision_manufacturing', subtitle: 'Track business assets, assignments, service and depreciation.', metrics: [['Total Assets','486'],['Asset Value','ZMW 8.4M'],['Due Service','12'],['Assigned','91%']], tabs: ['Asset Register','Assignments','Maintenance','Depreciation'] },
  'Fleet & Fuel': { icon: 'local_shipping', subtitle: 'Manage vehicles, trips, maintenance and fuel consumption.', metrics: [['Vehicles','42'],['On Route','18'],['Fuel This Month','12,480 L'],['Service Due','6']], tabs: ['Fleet','Trips','Fuel Logs','Maintenance','Drivers'] },
  Notifications: { icon: 'notifications_active', subtitle: 'Manage notification activity, channels and preferences.', metrics: [['Unread','12'],['Today','38'],['Critical','3'],['Delivery Rate','99.4%']], tabs: ['Inbox','Mentions','System','Preferences'] },
  'Developer Portal': { icon: 'terminal', subtitle: 'Build secure integrations with keys, webhooks and API tools.', metrics: [['Applications','6'],['API Keys','12'],['Requests Today','84.2K'],['Webhook Health','99.8%']], tabs: ['Overview','API Keys','Applications','Webhooks','API Logs'] },
  'SmartBiz Control Center': { icon: 'admin_panel_settings', subtitle: 'Operate organizations, licenses and platform health centrally.', metrics: [['Organizations','284'],['Active Users','18,420'],['Monthly Revenue','ZMW 2.8M'],['Platform Health','99.99%']], tabs: ['Organizations','Subscriptions','Modules','Feature Flags','Monitoring','Support'] },
  'Customer Portal': { icon: 'support_agent', subtitle: 'A self-service experience for invoices, statements and support.', metrics: [['Open Invoices','4'],['Outstanding','ZMW 18,420'],['Support Tickets','2'],['Loyalty Points','2,458']], tabs: ['Overview','Invoices','Payments','Statements','Support'] },
  'Employee Portal': { icon: 'person', subtitle: 'Employee self-service for payroll, leave and personal records.', metrics: [['Leave Balance','18 days'],['Next Pay Date','25 Sep'],['Open Requests','2'],['Documents','14']], tabs: ['My Profile','Payslips','Leave','Loans','Documents'] },
  'Product Detail': { icon: 'inventory_2', subtitle: 'Review stock movement, pricing and intelligent reorder guidance.', metrics: [['Available Stock','75 units'],['Stock Value','ZMW 13,875'],['Reorder Level','20 units'],['30 Day Sales','148 units']], tabs: ['Overview','Stock Movement','Suppliers','Pricing','Audit'] },
  'Invoice Detail': { icon: 'receipt_long', subtitle: 'Review billing, payment history and customer activity.', metrics: [['Invoice Total','ZMW 12,450'],['Paid','ZMW 12,450'],['Balance','ZMW 0'],['Status','Paid']], tabs: ['Line Items','Payments','Activity','Documents'] },
  'Customer Profile': { icon: 'domain', subtitle: 'Understand customer value, balances and commercial activity.', metrics: [['Total Purchases','ZMW 245,800'],['Outstanding','ZMW 12,450'],['Credit Limit','ZMW 75,000'],['Loyalty','2,458 pts']], tabs: ['Transactions','Invoices','Payments','Notes','Documents'] },
  'Stock Transfer': { icon: 'swap_horiz', subtitle: 'Move stock between branches with traceable approval controls.', metrics: [['Available Items','148'],['Source Branch','Lusaka Main'],['Destination','Kabwe'],['Transfer Status','Draft']], tabs: ['Transfer Items','Routing','Approval','History'] },
  'New Product': { icon: 'add_box', subtitle: 'Create a stocked or service product with pricing and reorder controls.', metrics: [['Required Fields','6'],['Warehouses','4'],['Tax Rate','16% VAT'],['Status','Draft']], tabs: ['Product Details','Pricing','Inventory','Suppliers'] },
  'New Employee': { icon: 'person_add', subtitle: 'Onboard an employee with organization, payroll and access details.', metrics: [['Onboarding Steps','4'],['Departments','8'],['Documents','5'],['Status','Draft']], tabs: ['Personal Details','Employment','Payroll','Documents'] },
}

const records = [
  ['SB-2026-0847','Lusaka Fresh Market','Updated today','Active'],
  ['SB-2026-0846','Copperbelt Operations','Yesterday','Pending'],
  ['SB-2026-0845','Kabwe Trading Co.','06 Sep 2026','Completed'],
  ['SB-2026-0844','Choma Agro Holdings','04 Sep 2026','Active'],
]

export default function ModuleWorkspace({ module = 'Workspace' }: Props) {
  const config = details[module] ?? { icon: 'grid_view', subtitle: 'Manage connected business operations.', metrics: [['Active Records','148'],['Pending','12'],['Completed','94%'],['Updated','Today']], tabs: ['Overview','Activity','Reports'] }
  const [tab, setTab] = useState(config.tabs[0])
  const [query, setQuery] = useState('')
  const [showCreate, setShowCreate] = useState(false)
  const rows = useMemo(() => records.filter(row => row.join(' ').toLowerCase().includes(query.toLowerCase())), [query])
  return <div className="px-4 sm:px-6 py-5 sm:py-7 pb-12">
    <div className="flex flex-wrap justify-between items-end gap-4">
      <div><div className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-[.16em] text-[#009b96]"><span className="material-symbols-outlined text-[17px]">{config.icon}</span>SmartBiz workspace</div><h1 className="text-[31px] font-bold tracking-tight text-slate-950 mt-2">{module}</h1><p className="text-slate-500 mt-1">{config.subtitle}</p></div>
      <Button onClick={() => setShowCreate(true)} className="w-full sm:w-auto"><span className="material-symbols-outlined">add</span>Create New</Button>
    </div>
    <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4 mt-7">{config.metrics.map(([label,value],i) => <Card key={label} className="metric-glow"><div className="flex justify-between"><p className="text-[11px] uppercase tracking-wider font-semibold text-slate-500">{label}</p><span className="w-8 h-8 rounded-xl bg-slate-100 text-slate-500 flex items-center justify-center"><span className="material-symbols-outlined text-[17px]">{['trending_up','schedule','monitoring','verified'][i]}</span></span></div><p className="text-[25px] font-bold mt-3 text-slate-950">{value}</p><p className="text-[11px] text-emerald-600 mt-1">Live prototype data</p></Card>)}</div>
    <Card noPadding className="mt-5 overflow-hidden">
      <div className="px-4 sm:px-5 pt-4 flex flex-wrap justify-between gap-4 border-b border-slate-200"><div className="flex gap-6 overflow-x-auto max-w-full">{config.tabs.map(item => <button key={item} onClick={() => setTab(item)} className={`pb-3 text-[13px] font-semibold whitespace-nowrap border-b-2 ${tab===item?'text-[#009b96] border-[#00cec8]':'text-slate-500 border-transparent'}`}>{item}</button>)}</div><Input className="w-full sm:w-60 mb-3" placeholder="Search records..." value={query} onChange={e => setQuery(e.target.value)}/></div>
      {rows.length ? <Table><Thead><tr><Th>Reference</Th><Th>Details</Th><Th>Updated</Th><Th>Status</Th><Th></Th></tr></Thead><tbody>{rows.map(row => <Tr key={row[0]}><Td className="font-bold text-[#009b96]">{row[0]}</Td><Td className="font-semibold">{row[1]}</Td><Td>{row[2]}</Td><Td><Badge variant={row[3]==='Pending'?'warning':'success'}>{row[3]}</Badge></Td><Td><Button variant="ghost" size="sm">View</Button></Td></Tr>)}</tbody></Table> : <EmptyState title="No matching records" description="Try another search term."/>}
    </Card>
    {showCreate && <div className="fixed inset-0 z-[220] bg-slate-950/45 backdrop-blur-sm flex items-center justify-center p-4" onClick={() => setShowCreate(false)}><Card className="w-full max-w-md" onClick={e => e.stopPropagation()}><div className="w-11 h-11 rounded-xl bg-[#00cec8]/15 text-[#009b96] flex items-center justify-center"><span className="material-symbols-outlined">add_task</span></div><h2 className="text-[22px] font-bold mt-4">Create {module} record</h2><p className="text-slate-500 mt-2">Start a new workflow using realistic prototype validation and local persistence.</p><div className="flex justify-end gap-2 mt-6"><Button variant="outline" onClick={() => setShowCreate(false)}>Cancel</Button><Button onClick={() => setShowCreate(false)}>Continue</Button></div></Card></div>}
  </div>
}
