import { useMemo, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { isDemoMode, supabase } from '@/shared/lib/supabase'
import { Badge, Card, EmptyState, PageHeader, Skeleton, Table, Td, Th, Thead, Tr } from '@/shared/components/ui/Display'
import { Button } from '@/shared/components/ui/Button'
import { Input } from '@/shared/components/ui/FormElements'

type AuditEvent = { id: string; organization_id: string | null; user_id: string | null; module: string; action: string; entity_type: string | null; entity_id: string | null; old_data: unknown; new_data: unknown; metadata: unknown; created_at: string; organization: { name: string } | null }
type AuditTab = 'all' | 'access' | 'changes' | 'exports'
const TABS: Array<{ key: AuditTab; label: string }> = [{key:'all',label:'All Events'},{key:'access',label:'Access'},{key:'changes',label:'Data Changes'},{key:'exports',label:'Exports'}]
const demoEvents: AuditEvent[] = [
  {id:'audit-1',organization_id:'demo',user_id:'admin-1',module:'security',action:'UPDATE',entity_type:'user_organization',entity_id:'member-1',old_data:{role:'member'},new_data:{role:'manager'},metadata:{source:'database_trigger'},created_at:new Date().toISOString(),organization:{name:'Lusaka Fresh Market'}},
  {id:'audit-2',organization_id:'demo',user_id:'admin-1',module:'reports',action:'EXPORT',entity_type:'vat_summary',entity_id:null,old_data:null,new_data:null,metadata:{format:'csv'},created_at:new Date(Date.now()-3600000).toISOString(),organization:{name:'Lusaka Fresh Market'}},
  {id:'audit-3',organization_id:'demo',user_id:'owner-1',module:'auth',action:'LOGIN',entity_type:'session',entity_id:null,old_data:null,new_data:null,metadata:{result:'success'},created_at:new Date(Date.now()-7200000).toISOString(),organization:{name:'Choma Agro Holdings'}},
]

function category(event: AuditEvent): Exclude<AuditTab,'all'> {
  const value = `${event.module} ${event.action} ${event.entity_type ?? ''}`.toLowerCase()
  if (value.includes('export') || value.includes('download')) return 'exports'
  if (value.includes('auth') || value.includes('login') || value.includes('access') || value.includes('user_organization') || value.includes('permission')) return 'access'
  return 'changes'
}

export default function PlatformAuditPage() {
  const [tab,setTab]=useState<AuditTab>('all'), [query,setQuery]=useState(''), [selected,setSelected]=useState<AuditEvent|null>(null)
  const {data:events=[],isLoading,error}=useQuery({queryKey:['platform-audit'],queryFn:async()=>{if(isDemoMode)return demoEvents;const{data,error}=await supabase.from('audit_log').select('id,organization_id,user_id,module,action,entity_type,entity_id,old_data,new_data,metadata,created_at,organization(name)').order('created_at',{ascending:false}).limit(500);if(error)throw error;return(data??[]) as unknown as AuditEvent[]}})
  const filtered=useMemo(()=>events.filter(event=>(tab==='all'||category(event)===tab)&&`${event.organization?.name??''} ${event.module} ${event.action} ${event.entity_type??''} ${event.user_id??''}`.toLowerCase().includes(query.toLowerCase())),[events,query,tab])
  const today=events.filter(event=>new Date(event.created_at).toDateString()===new Date().toDateString()).length
  return <div className="pb-12"><PageHeader title="Platform Audit" subtitle="Review access, data changes and exports across every organization." breadcrumb={[{label:'Platform Backoffice'},{label:'Audit'}]}/><div className="space-y-5 px-4 sm:px-6">
    <div className="grid gap-4 sm:grid-cols-3"><Card><p className="text-xs uppercase text-slate-500">Events today</p><p className="mt-2 text-2xl font-bold">{today}</p></Card><Card><p className="text-xs uppercase text-slate-500">Access events</p><p className="mt-2 text-2xl font-bold">{events.filter(e=>category(e)==='access').length}</p></Card><Card><p className="text-xs uppercase text-slate-500">Exports</p><p className="mt-2 text-2xl font-bold">{events.filter(e=>category(e)==='exports').length}</p></Card></div>
    <Card noPadding className="overflow-hidden"><div className="flex flex-wrap items-end justify-between gap-3 border-b border-slate-200 px-5 pt-4"><div className="flex max-w-full gap-5 overflow-x-auto">{TABS.map(item=><button key={item.key} onClick={()=>setTab(item.key)} className={`whitespace-nowrap border-b-2 pb-3 text-sm font-semibold ${tab===item.key?'border-[#00cec8] text-[#007f7a]':'border-transparent text-slate-500'}`}>{item.label}</button>)}</div><Input className="mb-3 w-full sm:w-72" placeholder="Search events…" value={query} onChange={event=>setQuery(event.target.value)}/></div>
      {isLoading?<div className="space-y-3 p-5">{[1,2,3].map(i=><Skeleton key={i} className="h-12"/>)}</div>:error?<EmptyState icon="error" title="Could not load audit events" description={(error as Error).message}/>:!filtered.length?<EmptyState icon="manage_search" title="No matching events" description="Try another category or search term."/>:<Table><Thead><tr><Th>Time</Th><Th>Organization</Th><Th>Event</Th><Th>Entity</Th><Th>Actor</Th><Th></Th></tr></Thead><tbody>{filtered.map(event=><Tr key={event.id}><Td>{new Date(event.created_at).toLocaleString('en-ZM')}</Td><Td>{event.organization?.name??'Platform'}</Td><Td><Badge variant={category(event)==='access'?'info':category(event)==='exports'?'warning':'default'}>{event.action}</Badge><span className="ml-2 text-xs text-slate-500">{event.module}</span></Td><Td>{event.entity_type??'—'}</Td><Td className="font-mono text-xs">{event.user_id?.slice(0,8)??'System'}</Td><Td><Button variant="ghost" size="sm" onClick={()=>setSelected(event)}>View</Button></Td></Tr>)}</tbody></Table>}
    </Card></div>{selected&&<div className="fixed inset-0 z-[300] flex justify-end bg-slate-950/50" onClick={()=>setSelected(null)}><aside className="h-full w-full max-w-xl overflow-y-auto bg-white p-6 shadow-2xl" onClick={event=>event.stopPropagation()}><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-[#008f88]">Audit event</p><h2 className="mt-1 text-2xl font-bold">{selected.action} · {selected.module}</h2><p className="mt-1 text-sm text-slate-500">{new Date(selected.created_at).toLocaleString('en-ZM')}</p></div><Button variant="ghost" size="icon" aria-label="Close details" onClick={()=>setSelected(null)}><span className="material-symbols-outlined">close</span></Button></div><dl className="mt-6 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-slate-500">Organization</dt><dd className="font-semibold">{selected.organization?.name??'Platform'}</dd></div><div><dt className="text-slate-500">Actor</dt><dd className="break-all font-mono text-xs">{selected.user_id??'System'}</dd></div><div><dt className="text-slate-500">Entity</dt><dd className="font-semibold">{selected.entity_type??'—'}</dd></div><div><dt className="text-slate-500">Entity ID</dt><dd className="break-all font-mono text-xs">{selected.entity_id??'—'}</dd></div></dl><JsonBlock title="Previous value" value={selected.old_data}/><JsonBlock title="New value" value={selected.new_data}/><JsonBlock title="Metadata" value={selected.metadata}/></aside></div>}</div>
}
function JsonBlock({title,value}:{title:string;value:unknown}){return <div className="mt-6"><h3 className="mb-2 text-sm font-bold">{title}</h3><pre className="max-h-72 overflow-auto rounded-xl bg-slate-950 p-4 text-xs text-slate-100">{value==null?'No data':JSON.stringify(value,null,2)}</pre></div>}
